# This is a basic workflow to help you get started with Actions

name: build-page-branch

# Controls when the workflow will run
on:
    push:
        branches: [main]
    # The below rule invokes when ANY pull request is made to main
    # This is DANGEROUS and can allow for malicious behavior
    # pull_request:
    #   branches: [main]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest
        # Use production environment specified in GitHub settings
        environment: production
        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v3.0.0

            # Builds the react site for github pages
            - name: Build Static Pages
              run: |
                  npm ci
                  npm run build
                  mv build/public docs
                  echo "# DO NOT MANUALLY PUSH TO THIS BRANCH, ANY WORK DONE WILL BE ERASED. ITS WORK COMES FROM MASTER AND IT WILL BE REWRITTEN THE NEXT TIME AN ACTION OCCURS ON THE MASTER BRANCH" > README.md
            - name: Push to Deployment Branch
              run: |
                  git stash
                  git checkout -b page
                  git stash pop
                  git add .
                  git commit -m "Deploy Site"
                  git push origin page --force
